/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 model4.glb -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    arrow_light_2_brake_light_0: THREE.Mesh
    polymsh73_2_INT_Plastica_FLAT_0: THREE.Mesh
    polymsh74_2_INT_Plastica_FLAT_0: THREE.Mesh
    CINTURE_OFF_SUB0_INT_Cinture_0: THREE.Mesh
    CINTURE_OFF_SUB1_INT_Plastica_Grigia_0: THREE.Mesh
    CINTURE_OFF_SUB2_INT_Cromato_0: THREE.Mesh
    CINTURE_ON_SUB1_INT_Plastica_Grigia_0: THREE.Mesh
    CINTURE_ON_SUB2_INT_Cromato_0: THREE.Mesh
    cube_SUB0_INT_Plastica_Grigia_0: THREE.Mesh
    cube_SUB1_INT_Navigatore_0: THREE.Mesh
    cube_SUB10_INT_Pelle_Plasticata_0: THREE.Mesh
    cube_SUB11_INT_FlatBlack_0: THREE.Mesh
    cube_SUB12_INT_Metallo_semiopaco_0: THREE.Mesh
    cube_SUB13_INT_Speakers_0: THREE.Mesh
    cube_SUB14_INT_display_0: THREE.Mesh
    cube_SUB15_INT_Plastica_ROSSA_Ref_0: THREE.Mesh
    cube_SUB16_INT_Carpet_0: THREE.Mesh
    cube_SUB17_INT_Speakers_GRID_0: THREE.Mesh
    cube_SUB18_INT_Tessuto1_0: THREE.Mesh
    cube_SUB19_Carpaint_Main_0: THREE.Mesh
    cube_SUB2_INT_Vetro_0: THREE.Mesh
    cube_SUB20_INT_Gomma_0: THREE.Mesh
    cube_SUB21_INT_Pedali_NM_0: THREE.Mesh
    cube_SUB22_Mirror_0: THREE.Mesh
    cube_SUB23_INT_LOGHI_metallici_0: THREE.Mesh
    cube_SUB24_INT_LOGHI_Plastica_0: THREE.Mesh
    cube_SUB25_INT_Tessuto2_0: THREE.Mesh
    cube_SUB26_INT_Plastica_ROSSA_0: THREE.Mesh
    cube_SUB3_INT_Decals_0: THREE.Mesh
    cube_SUB4_INT_Plastica_Scuro_0: THREE.Mesh
    cube_SUB5_INT_CARBON_fine_0: THREE.Mesh
    cube_SUB6_INT_alluminio_0: THREE.Mesh
    cube_SUB7_INT_Plastica_NERA_Ref_0: THREE.Mesh
    cube_SUB8_INT_Cromato_0: THREE.Mesh
    cube_SUB9_INT_Pelle_Morbida_0: THREE.Mesh
    FUEL_LED_1_2_INT_display_0: THREE.Mesh
    FUEL_LED_2_2_INT_display_0: THREE.Mesh
    FUEL_LED_3_2_INT_display_0: THREE.Mesh
    FUEL_LED_4_2_INT_display_0: THREE.Mesh
    FUEL_LED_5_2_INT_display_0: THREE.Mesh
    GEO_Display_2_INT_display_0: THREE.Mesh
    limit1_2_INT_LED_0: THREE.Mesh
    limit2_2_INT_LED_0: THREE.Mesh
    limit3_2_INT_LED_0: THREE.Mesh
    LOGHI_sedili_2_INT_LOGO_Sedile_0: THREE.Mesh
    polymsh72_SUB0_INT_Plastica_Grigia_0: THREE.Mesh
    polymsh72_SUB1_INT_Cromato_0: THREE.Mesh
    polymsh_detached_2_INT_Cinture_0: THREE.Mesh
    polymsh_detached39_2_INT_Cuciture_0: THREE.Mesh
    guaina_cambio_SUB0_INT_Cuciture_RIG_0: THREE.Mesh
    guaina_cambio_SUB1_INT_Pelle_Morbida_skin_0: THREE.Mesh
    polymsh_extracted_SUB0_INT_Decals_0: THREE.Mesh
    polymsh_extracted_SUB1_INT_Asta_Cambio_0: THREE.Mesh
    polymsh_extracted_SUB2_INT_Plastica_Scuro_0: THREE.Mesh
    polymsh_extracted_SUB3_INT_Cromato_0: THREE.Mesh
    polymsh_extracted3_SUB0_INT_Pelle_Morbida_0: THREE.Mesh
    polymsh_extracted3_SUB1_INT_CARBON_fine_0: THREE.Mesh
    polymsh_extracted3_SUB2_INT_Cuciture_0: THREE.Mesh
    polymsh_extracted3_SUB3_INT_Pelle_Plasticata_0: THREE.Mesh
    polymsh_extracted3_SUB4_INT_Plastica_Scuro_0: THREE.Mesh
    polymsh_extracted3_SUB5_INT_Decals_NM_0: THREE.Mesh
    polymsh_extracted3_SUB6_INT_LOGO_Volante_0: THREE.Mesh
    polymsh_extracted3_SUB7_INT_Decals_0: THREE.Mesh
    TAG_WATER_0_2_INT_display_0: THREE.Mesh
    TAG_WATER_1_2_INT_display_0: THREE.Mesh
    TAG_WATER_10_2_INT_display_0: THREE.Mesh
    TAG_WATER_11_2_INT_display_0: THREE.Mesh
    TAG_WATER_2_2_INT_display_0: THREE.Mesh
    TAG_WATER_3_2_INT_display_0: THREE.Mesh
    TAG_WATER_4_2_INT_display_0: THREE.Mesh
    TAG_WATER_5_2_INT_display_0: THREE.Mesh
    TAG_WATER_6_2_INT_display_0: THREE.Mesh
    TAG_WATER_7_2_INT_display_0: THREE.Mesh
    TAG_WATER_8_2_INT_display_0: THREE.Mesh
    TAG_WATER_9_2_INT_display_0: THREE.Mesh
    GEO_Cockpit_SUB1_Carpaint_Main_0: THREE.Mesh
    g_Brake_Disk_LF_2_Brake_Disk_0: THREE.Mesh
    g_Brake_Disk_LR_2_Brake_Disk_0: THREE.Mesh
    g_Brake_Disk_RF_2_Brake_Disk_0: THREE.Mesh
    g_Brake_Disk_RR_2_Brake_Disk_0: THREE.Mesh
    polymsh_detached27_SUB0_INT_Speakers_GRID_0: THREE.Mesh
    polymsh_detached27_SUB1_INT_Pelle_Morbida_0: THREE.Mesh
    polymsh_detached27_SUB10_INT_Decals_NM_0: THREE.Mesh
    polymsh_detached27_SUB11_INT_Speakers_0: THREE.Mesh
    polymsh_detached27_SUB12_INT_Decals_0: THREE.Mesh
    polymsh_detached27_SUB13_INT_Cuciture_0: THREE.Mesh
    polymsh_detached27_SUB14_INT_Glass_side_0: THREE.Mesh
    polymsh_detached27_SUB2_Carpaint_Main_0: THREE.Mesh
    polymsh_detached27_SUB3_INT_Metallo_semiopaco_0: THREE.Mesh
    polymsh_detached27_SUB4_INT_Maniglia_0: THREE.Mesh
    polymsh_detached27_SUB5_INT_Plastica_Grigia_0: THREE.Mesh
    polymsh_detached27_SUB6_INT_Pelle_Plasticata_0: THREE.Mesh
    polymsh_detached27_SUB7_INT_Cromato_0: THREE.Mesh
    polymsh_detached27_SUB8_INT_FlatBlack_0: THREE.Mesh
    polymsh_detached27_SUB9_INT_Plastica_NERA_Ref_0: THREE.Mesh
    g_DOOR_EXT_L_SUB0_Rubber_Black_0: THREE.Mesh
    g_DOOR_EXT_L_SUB1_Glass_0: THREE.Mesh
    g_DOOR_EXT_L_SUB2_Carpaint_Main_0: THREE.Mesh
    g_DOOR_EXT_L_SUB3_Plastic_Black_0: THREE.Mesh
    g_DOOR_EXT_L_SUB4_Mirror_0: THREE.Mesh
    polymsh_detached26_SUB0_INT_Plastica_Grigia_0: THREE.Mesh
    polymsh_detached26_SUB1_INT_Pelle_Morbida_0: THREE.Mesh
    polymsh_detached26_SUB10_INT_Decals_0: THREE.Mesh
    polymsh_detached26_SUB11_INT_Cuciture_0: THREE.Mesh
    polymsh_detached26_SUB12_INT_Glass_side_0: THREE.Mesh
    polymsh_detached26_SUB2_INT_Speakers_GRID_0: THREE.Mesh
    polymsh_detached26_SUB3_INT_Maniglia_0: THREE.Mesh
    polymsh_detached26_SUB4_Carpaint_Main_0: THREE.Mesh
    polymsh_detached26_SUB5_INT_Metallo_semiopaco_0: THREE.Mesh
    polymsh_detached26_SUB6_INT_Pelle_Plasticata_0: THREE.Mesh
    polymsh_detached26_SUB7_INT_Speakers_0: THREE.Mesh
    polymsh_detached26_SUB8_INT_Cromato_0: THREE.Mesh
    polymsh_detached26_SUB9_INT_FlatBlack_0: THREE.Mesh
    polymsh58_SUB0_Glass_0: THREE.Mesh
    polymsh58_SUB1_Carpaint_Main_0: THREE.Mesh
    polymsh58_SUB2_Rubber_Black_0: THREE.Mesh
    polymsh58_SUB3_Mirror_0: THREE.Mesh
    polymsh58_SUB4_Plastic_Black_0: THREE.Mesh
    g_BUMPER_F_SUB0_Details_0: THREE.Mesh
    g_BUMPER_F_SUB1_Grids_0: THREE.Mesh
    g_BUMPER_F_SUB2_Carpaint_Main_0: THREE.Mesh
    g_HeadLights_SUB0_Chrome_0: THREE.Mesh
    g_HeadLights_SUB1_front_light1_0: THREE.Mesh
    front_light1_2_front_light1_0: THREE.Mesh
    front_light2_2_INT_Glass_side_0: THREE.Mesh
    front_light3_2_front_light1_0: THREE.Mesh
    g_BODY_EXT_SUB0_Details_0: THREE.Mesh
    g_BODY_EXT_SUB1_Plastic_Black_0: THREE.Mesh
    g_BODY_EXT_SUB10_Lotus_Performance_Logo_0: THREE.Mesh
    g_BODY_EXT_SUB2_Engine_Cover_0: THREE.Mesh
    g_BODY_EXT_SUB3_Glass_0: THREE.Mesh
    g_BODY_EXT_SUB3_1_INT_Glass_side_0: THREE.Mesh
    g_BODY_EXT_SUB4_Rubber_Black_0: THREE.Mesh
    g_BODY_EXT_SUB5_Chrome_0: THREE.Mesh
    g_BODY_EXT_SUB6_Grids_0: THREE.Mesh
    g_BODY_EXT_SUB7_Carpaint_Black_0: THREE.Mesh
    g_BODY_EXT_SUB8_INT_Glass_side_0: THREE.Mesh
    g_BODY_EXT_SUB9_Carpaint_Main_0: THREE.Mesh
    g_TRUNK_SUB0_Details_0: THREE.Mesh
    g_TRUNK_SUB1_Grids_0: THREE.Mesh
    g_TRUNK_SUB2_Badges_0: THREE.Mesh
    g_TRUNK_SUB3_Carpaint_Main_0: THREE.Mesh
    polymsh_detached32_2_Glass_0: THREE.Mesh
    g_BUMPER_R_SUB0_Carpaint_Main_0: THREE.Mesh
    g_BUMPER_R_SUB1_Details_0: THREE.Mesh
    g_BUMPER_R_SUB2_Plastic_Black_0: THREE.Mesh
    g_RearLights_2_brake_light_0: THREE.Mesh
    REAR_LIGHT_1_2_brake_light_0: THREE.Mesh
    REAR_LIGHT_2_2_brake_light_0: THREE.Mesh
    retro_light_2_brake_light_0: THREE.Mesh
    g_Susp_ALever_LF_2_Details_0: THREE.Mesh
    g_Susp_Dump_LF_2_Details_0: THREE.Mesh
    g_Susp_Steering_LF_2_Details_0: THREE.Mesh
    g_Wheel_Hub_LF_SUB0_Details_0: THREE.Mesh
    g_Wheel_Hub_LF_SUB1_Brake_Caliper_0: THREE.Mesh
    g_Susp_ALever_LR_2_Details_0: THREE.Mesh
    g_Susp_Dump_LR_2_Details_0: THREE.Mesh
    g_Susp_Gear_LR_2_Details_0: THREE.Mesh
    g_Susp_Lever_LR_2_Details_0: THREE.Mesh
    g_Susp_Torsion_LR_2_Details_0: THREE.Mesh
    g_Wheel_Hub_LR_SUB0_Details_0: THREE.Mesh
    g_Wheel_Hub_LR_SUB1_Brake_Caliper_0: THREE.Mesh
    g_Susp_ALever_RF_2_Details_0: THREE.Mesh
    g_Susp_Dump_RF_2_Details_0: THREE.Mesh
    g_Susp_Steering_RF_2_Details_0: THREE.Mesh
    g_Wheel_Hub_RF_SUB0_Details_0: THREE.Mesh
    g_Wheel_Hub_RF_SUB1_Brake_Caliper_0: THREE.Mesh
    g_Susp_ALever_RR_2_Details_0: THREE.Mesh
    g_Susp_Dump_RR_2_Details_0: THREE.Mesh
    g_Susp_Gear_RR_2_Details_0: THREE.Mesh
    g_Susp_Lever_RR_2_Details_0: THREE.Mesh
    g_Wheel_Hub_RR_SUB0_Details_0: THREE.Mesh
    g_Wheel_Hub_RR_SUB1_Brake_Caliper_0: THREE.Mesh
    g_RIM_LF_2_Carpaint_Main_0: THREE.Mesh
    g_Wheel_Tyre_Tread_LF_2_Tyre_Tread_0: THREE.Mesh
    g_RIM_LR_2_Carpaint_Main_0: THREE.Mesh
    g_Wheel_Tyre_Tread_LR_2_Tyre_Tread_0: THREE.Mesh
    g_RIM_RF_2_Carpaint_Main_0: THREE.Mesh
    g_Wheel_Tyre_Tread_RF_2_Tyre_Tread_0: THREE.Mesh
    g_RIM_RR_2_Carpaint_Main_0: THREE.Mesh
    g_Wheel_Tyre_Tread_RR_2_Tyre_Tread_0: THREE.Mesh
    g_WIPER_2_Rubber_Black_0: THREE.Mesh
    polymsh_detached29_2_Rubber_Black_0: THREE.Mesh
  }
  materials: {
    brake_light: THREE.MeshStandardMaterial
    INT_Plastica_FLAT: THREE.MeshStandardMaterial
    INT_Cinture: THREE.MeshStandardMaterial
    INT_Plastica_Grigia: THREE.MeshStandardMaterial
    INT_Cromato: THREE.MeshStandardMaterial
    INT_Navigatore: THREE.MeshStandardMaterial
    INT_Pelle_Plasticata: THREE.MeshStandardMaterial
    INT_FlatBlack: THREE.MeshStandardMaterial
    INT_Metallo_semiopaco: THREE.MeshStandardMaterial
    INT_Speakers: THREE.MeshStandardMaterial
    INT_display: THREE.MeshStandardMaterial
    INT_Plastica_ROSSA_Ref: THREE.MeshStandardMaterial
    INT_Carpet: THREE.MeshStandardMaterial
    INT_Speakers_GRID: THREE.MeshStandardMaterial
    INT_Tessuto1: THREE.MeshStandardMaterial
    Carpaint_Main_0: THREE.MeshStandardMaterial
    ['INT_Vetro.001']: THREE.MeshStandardMaterial
    INT_Gomma: THREE.MeshStandardMaterial
    INT_Pedali_NM: THREE.MeshStandardMaterial
    Mirror: THREE.MeshStandardMaterial
    INT_LOGHI_metallici: THREE.MeshStandardMaterial
    INT_LOGHI_Plastica: THREE.MeshStandardMaterial
    INT_Tessuto2: THREE.MeshStandardMaterial
    INT_Plastica_ROSSA: THREE.MeshStandardMaterial
    INT_Decals: THREE.MeshStandardMaterial
    INT_Plastica_Scuro: THREE.MeshStandardMaterial
    INT_CARBON_fine: THREE.MeshStandardMaterial
    INT_alluminio: THREE.MeshStandardMaterial
    INT_Plastica_NERA_Ref: THREE.MeshStandardMaterial
    INT_Pelle_Morbida: THREE.MeshStandardMaterial
    INT_LED: THREE.MeshStandardMaterial
    INT_LOGO_Sedile: THREE.MeshStandardMaterial
    INT_Cuciture: THREE.MeshStandardMaterial
    INT_Cuciture_RIG: THREE.MeshStandardMaterial
    INT_Pelle_Morbida_skin: THREE.MeshStandardMaterial
    INT_Asta_Cambio: THREE.MeshStandardMaterial
    INT_Decals_NM: THREE.MeshStandardMaterial
    INT_LOGO_Volante: THREE.MeshStandardMaterial
    Brake_Disk: THREE.MeshStandardMaterial
    INT_Glass_side: THREE.MeshStandardMaterial
    INT_Maniglia: THREE.MeshStandardMaterial
    Rubber_Black: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    Plastic_Black: THREE.MeshStandardMaterial
    Details: THREE.MeshStandardMaterial
    Grids: THREE.MeshStandardMaterial
    Chrome: THREE.MeshStandardMaterial
    front_light1: THREE.MeshStandardMaterial
    Lotus_Performance_Logo: THREE.MeshStandardMaterial
    Engine_Cover: THREE.MeshStandardMaterial
    Carpaint_Black: THREE.MeshStandardMaterial
    Badges: THREE.MeshStandardMaterial
    Brake_Caliper: THREE.MeshStandardMaterial
    Carpaint_Main: THREE.MeshStandardMaterial
    Tyre_Tread: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model4(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model4.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[78.749, 31.851, 120.457]}>
          <mesh
            geometry={nodes.g_Brake_Disk_LF_2_Brake_Disk_0.geometry}
            material={materials.Brake_Disk}
            position={[0, 0, -0.002]}
          />
        </group>
        <group position={[78.749, 33.225, -141.953]}>
          <mesh
            geometry={nodes.g_Brake_Disk_LR_2_Brake_Disk_0.geometry}
            material={materials.Brake_Disk}
            position={[0, 0, -0.001]}
          />
        </group>
        <group position={[-78.749, 31.851, 120.457]}>
          <mesh
            geometry={nodes.g_Brake_Disk_RF_2_Brake_Disk_0.geometry}
            material={materials.Brake_Disk}
            position={[0, 0, -0.002]}
          />
        </group>
        <group position={[-78.749, 33.225, -141.953]}>
          <mesh
            geometry={nodes.g_Brake_Disk_RR_2_Brake_Disk_0.geometry}
            material={materials.Brake_Disk}
            position={[0, 0, -0.001]}
          />
        </group>
        <group position={[86.85, 59.483, 65.317]}>
          <mesh
            geometry={nodes.polymsh_detached27_SUB0_INT_Speakers_GRID_0.geometry}
            material={materials.INT_Speakers_GRID}
          />
          <mesh
            geometry={nodes.polymsh_detached27_SUB1_INT_Pelle_Morbida_0.geometry}
            material={materials.INT_Pelle_Morbida}
          />
          <mesh geometry={nodes.polymsh_detached27_SUB10_INT_Decals_NM_0.geometry} material={materials.INT_Decals_NM} />
          <mesh geometry={nodes.polymsh_detached27_SUB11_INT_Speakers_0.geometry} material={materials.INT_Speakers} />
          <mesh geometry={nodes.polymsh_detached27_SUB12_INT_Decals_0.geometry} material={materials.INT_Decals} />
          <mesh geometry={nodes.polymsh_detached27_SUB13_INT_Cuciture_0.geometry} material={materials.INT_Cuciture} />
          <mesh
            geometry={nodes.polymsh_detached27_SUB14_INT_Glass_side_0.geometry}
            material={materials.INT_Glass_side}
          />
          <mesh
            geometry={nodes.polymsh_detached27_SUB2_Carpaint_Main_0.geometry}
            material={materials.Carpaint_Main_0}
          />
          <mesh
            geometry={nodes.polymsh_detached27_SUB3_INT_Metallo_semiopaco_0.geometry}
            material={materials.INT_Metallo_semiopaco}
          />
          <mesh geometry={nodes.polymsh_detached27_SUB4_INT_Maniglia_0.geometry} material={materials.INT_Maniglia} />
          <mesh
            geometry={nodes.polymsh_detached27_SUB5_INT_Plastica_Grigia_0.geometry}
            material={materials.INT_Plastica_Grigia}
          />
          <mesh
            geometry={nodes.polymsh_detached27_SUB6_INT_Pelle_Plasticata_0.geometry}
            material={materials.INT_Pelle_Plasticata}
          />
          <mesh geometry={nodes.polymsh_detached27_SUB7_INT_Cromato_0.geometry} material={materials.INT_Cromato} />
          <mesh geometry={nodes.polymsh_detached27_SUB8_INT_FlatBlack_0.geometry} material={materials.INT_FlatBlack} />
          <mesh
            geometry={nodes.polymsh_detached27_SUB9_INT_Plastica_NERA_Ref_0.geometry}
            material={materials.INT_Plastica_NERA_Ref}
          />
          <mesh geometry={nodes.g_DOOR_EXT_L_SUB0_Rubber_Black_0.geometry} material={materials.Rubber_Black} />
          <mesh geometry={nodes.g_DOOR_EXT_L_SUB1_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.g_DOOR_EXT_L_SUB2_Carpaint_Main_0.geometry} material={materials.Carpaint_Main_0} />
          <mesh geometry={nodes.g_DOOR_EXT_L_SUB3_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
          <mesh geometry={nodes.g_DOOR_EXT_L_SUB4_Mirror_0.geometry} material={materials.Mirror} />
        </group>
        <group position={[-86.848, 59.483, 65.317]}>
          <mesh
            geometry={nodes.polymsh_detached26_SUB0_INT_Plastica_Grigia_0.geometry}
            material={materials.INT_Plastica_Grigia}
          />
          <mesh
            geometry={nodes.polymsh_detached26_SUB1_INT_Pelle_Morbida_0.geometry}
            material={materials.INT_Pelle_Morbida}
          />
          <mesh geometry={nodes.polymsh_detached26_SUB10_INT_Decals_0.geometry} material={materials.INT_Decals} />
          <mesh geometry={nodes.polymsh_detached26_SUB11_INT_Cuciture_0.geometry} material={materials.INT_Cuciture} />
          <mesh
            geometry={nodes.polymsh_detached26_SUB12_INT_Glass_side_0.geometry}
            material={materials.INT_Glass_side}
          />
          <mesh
            geometry={nodes.polymsh_detached26_SUB2_INT_Speakers_GRID_0.geometry}
            material={materials.INT_Speakers_GRID}
          />
          <mesh geometry={nodes.polymsh_detached26_SUB3_INT_Maniglia_0.geometry} material={materials.INT_Maniglia} />
          <mesh
            geometry={nodes.polymsh_detached26_SUB4_Carpaint_Main_0.geometry}
            material={materials.Carpaint_Main_0}
          />
          <mesh
            geometry={nodes.polymsh_detached26_SUB5_INT_Metallo_semiopaco_0.geometry}
            material={materials.INT_Metallo_semiopaco}
          />
          <mesh
            geometry={nodes.polymsh_detached26_SUB6_INT_Pelle_Plasticata_0.geometry}
            material={materials.INT_Pelle_Plasticata}
          />
          <mesh geometry={nodes.polymsh_detached26_SUB7_INT_Speakers_0.geometry} material={materials.INT_Speakers} />
          <mesh geometry={nodes.polymsh_detached26_SUB8_INT_Cromato_0.geometry} material={materials.INT_Cromato} />
          <mesh geometry={nodes.polymsh_detached26_SUB9_INT_FlatBlack_0.geometry} material={materials.INT_FlatBlack} />
          <mesh geometry={nodes.polymsh58_SUB0_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.polymsh58_SUB1_Carpaint_Main_0.geometry} material={materials.Carpaint_Main_0} />
          <mesh geometry={nodes.polymsh58_SUB2_Rubber_Black_0.geometry} material={materials.Rubber_Black} />
          <mesh geometry={nodes.polymsh58_SUB3_Mirror_0.geometry} material={materials.Mirror} />
          <mesh geometry={nodes.polymsh58_SUB4_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
        </group>
        <group position={[0, 57.968, 211.99]}>
          <mesh geometry={nodes.g_BUMPER_F_SUB0_Details_0.geometry} material={materials.Details} />
          <mesh geometry={nodes.g_BUMPER_F_SUB1_Grids_0.geometry} material={materials.Grids} />
          <mesh geometry={nodes.g_BUMPER_F_SUB2_Carpaint_Main_0.geometry} material={materials.Carpaint_Main_0} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, -139.689, 65.248]}>
            <mesh geometry={nodes.g_HeadLights_SUB0_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.g_HeadLights_SUB1_front_light1_0.geometry} material={materials.front_light1} />
          </group>
        </group>
        <group position={[0, 83.841, 65.269]}>
          <mesh geometry={nodes.g_TRUNK_SUB0_Details_0.geometry} material={materials.Details} />
          <mesh geometry={nodes.g_TRUNK_SUB1_Grids_0.geometry} material={materials.Grids} />
          <mesh geometry={nodes.g_TRUNK_SUB2_Badges_0.geometry} material={materials.Badges} />
          <mesh geometry={nodes.g_TRUNK_SUB3_Carpaint_Main_0.geometry} material={materials.Carpaint_Main_0} />
        </group>
        <group position={[0, 85.722, -210.965]}>
          <mesh geometry={nodes.g_BUMPER_R_SUB0_Carpaint_Main_0.geometry} material={materials.Carpaint_Main_0} />
          <mesh geometry={nodes.g_BUMPER_R_SUB1_Details_0.geometry} material={materials.Details} />
          <mesh geometry={nodes.g_BUMPER_R_SUB2_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.g_RearLights_2_brake_light_0.geometry}
            material={materials.brake_light}
            position={[0, 200.415, 81.405]}
          />
        </group>
        <group position={[78.749, 31.851, 120.457]}>
          <mesh
            geometry={nodes.g_Susp_ALever_LF_2_Details_0.geometry}
            material={materials.Details}
            position={[-30.576, -9.371, 10.385]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.g_Susp_Dump_LF_2_Details_0.geometry}
            material={materials.Details}
            position={[-26.973, 21.942, 1.43]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.g_Susp_Steering_LF_2_Details_0.geometry}
            material={materials.Details}
            position={[-32.781, -6.771, 13.21]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <group position={[0.853, 0, -0.002]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.g_Wheel_Hub_LF_SUB0_Details_0.geometry} material={materials.Details} />
            <mesh geometry={nodes.g_Wheel_Hub_LF_SUB1_Brake_Caliper_0.geometry} material={materials.Brake_Caliper} />
          </group>
        </group>
        <group position={[78.749, 33.225, -141.953]}>
          <mesh
            geometry={nodes.g_Susp_ALever_LR_2_Details_0.geometry}
            material={materials.Details}
            position={[-28.611, -10.312, 23.657]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.g_Susp_Dump_LR_2_Details_0.geometry}
            material={materials.Details}
            position={[-27.041, 25.578, 9.988]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.g_Susp_Gear_LR_2_Details_0.geometry}
            material={materials.Details}
            position={[-31.744, 4.652, 0.024]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.g_Susp_Lever_LR_2_Details_0.geometry}
            material={materials.Details}
            position={[-33.482, -3.994, -10.021]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.g_Susp_Torsion_LR_2_Details_0.geometry}
            material={materials.Details}
            position={[-78.749, -33.225, 141.953]}
          />
          <group position={[0, 0, -0.001]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.g_Wheel_Hub_LR_SUB0_Details_0.geometry} material={materials.Details} />
            <mesh geometry={nodes.g_Wheel_Hub_LR_SUB1_Brake_Caliper_0.geometry} material={materials.Brake_Caliper} />
          </group>
        </group>
        <group position={[-78.749, 31.851, 120.457]}>
          <mesh
            geometry={nodes.g_Susp_ALever_RF_2_Details_0.geometry}
            material={materials.Details}
            position={[30.576, -9.371, 10.385]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.g_Susp_Dump_RF_2_Details_0.geometry}
            material={materials.Details}
            position={[26.973, 21.942, 1.43]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.g_Susp_Steering_RF_2_Details_0.geometry}
            material={materials.Details}
            position={[32.781, -6.771, 13.21]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <group position={[-0.853, 0, -0.002]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.g_Wheel_Hub_RF_SUB0_Details_0.geometry} material={materials.Details} />
            <mesh geometry={nodes.g_Wheel_Hub_RF_SUB1_Brake_Caliper_0.geometry} material={materials.Brake_Caliper} />
          </group>
        </group>
        <group position={[-78.749, 33.225, -141.953]}>
          <mesh
            geometry={nodes.g_Susp_ALever_RR_2_Details_0.geometry}
            material={materials.Details}
            position={[28.611, -10.312, 23.657]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.g_Susp_Dump_RR_2_Details_0.geometry}
            material={materials.Details}
            position={[27.041, 25.578, 9.988]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.g_Susp_Gear_RR_2_Details_0.geometry}
            material={materials.Details}
            position={[31.744, 4.652, 0.024]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.g_Susp_Lever_RR_2_Details_0.geometry}
            material={materials.Details}
            position={[33.482, -3.994, -10.021]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <group position={[0, 0, -0.001]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.g_Wheel_Hub_RR_SUB0_Details_0.geometry} material={materials.Details} />
            <mesh geometry={nodes.g_Wheel_Hub_RR_SUB1_Brake_Caliper_0.geometry} material={materials.Brake_Caliper} />
          </group>
        </group>
        <group position={[78.749, 31.851, 120.457]}>
          <group position={[-2.767, 0, -0.002]}>
            <mesh
              geometry={nodes.g_RIM_LF_2_Carpaint_Main_0.geometry}
              material={materials.Carpaint_Main}
              position={[0, -0.008, 0]}
            />
          </group>
          <mesh
            geometry={nodes.g_Wheel_Tyre_Tread_LF_2_Tyre_Tread_0.geometry}
            material={materials.Tyre_Tread}
            position={[-2.767, 0, 0]}
          />
        </group>
        <group position={[78.749, 33.225, -141.953]}>
          <mesh
            geometry={nodes.g_RIM_LR_2_Carpaint_Main_0.geometry}
            material={materials.Carpaint_Main}
            position={[0, 0, -0.001]}
          />
          <mesh
            geometry={nodes.g_Wheel_Tyre_Tread_LR_2_Tyre_Tread_0.geometry}
            material={materials.Tyre_Tread}
            position={[-78.749, -33.225, 141.953]}
          />
        </group>
        <group position={[-78.749, 31.851, 120.457]}>
          <mesh
            geometry={nodes.g_RIM_RF_2_Carpaint_Main_0.geometry}
            material={materials.Carpaint_Main}
            position={[0, 0, -0.002]}
          />
          <mesh
            geometry={nodes.g_Wheel_Tyre_Tread_RF_2_Tyre_Tread_0.geometry}
            material={materials.Tyre_Tread}
            position={[78.749, -31.851, -120.457]}
          />
        </group>
        <group position={[-78.749, 33.225, -141.953]}>
          <mesh
            geometry={nodes.g_RIM_RR_2_Carpaint_Main_0.geometry}
            material={materials.Carpaint_Main}
            position={[0, 0, -0.001]}
          />
          <mesh
            geometry={nodes.g_Wheel_Tyre_Tread_RR_2_Tyre_Tread_0.geometry}
            material={materials.Tyre_Tread}
            position={[78.749, -33.225, 141.953]}
          />
        </group>
        <group position={[3.009, 74.819, 120.524]} rotation={[0.68, -0.942, 3.08]}>
          <group position={[-0.747, 10.69, -59.614]} rotation={[0.377, 0, 0.124]}>
            <mesh
              geometry={nodes.polymsh_detached29_2_Rubber_Black_0.geometry}
              material={materials.Rubber_Black}
              position={[47.695, 124.435, -14.002]}
              rotation={[0.51, -0.695, -2.517]}
            />
          </group>
          <mesh geometry={nodes.g_WIPER_2_Rubber_Black_0.geometry} material={materials.Rubber_Black} />
        </group>
        <mesh geometry={nodes.arrow_light_2_brake_light_0.geometry} material={materials.brake_light} />
        <mesh
          geometry={nodes.polymsh73_2_INT_Plastica_FLAT_0.geometry}
          material={materials.INT_Plastica_FLAT}
          position={[35.332, 82.293, 56.796]}
          rotation={[0.389, 0, -2.006]}
        />
        <mesh
          geometry={nodes.polymsh74_2_INT_Plastica_FLAT_0.geometry}
          material={materials.INT_Plastica_FLAT}
          position={[24.904, 82.293, 56.796]}
          rotation={[0.389, 0, -1.921]}
        />
        <group position={[30.228, 78.133, 29.782]} rotation={[0.264, 0, 0]}>
          <mesh
            geometry={nodes.polymsh_extracted3_SUB0_INT_Pelle_Morbida_0.geometry}
            material={materials.INT_Pelle_Morbida}
          />
          <mesh
            geometry={nodes.polymsh_extracted3_SUB1_INT_CARBON_fine_0.geometry}
            material={materials.INT_CARBON_fine}
          />
          <mesh geometry={nodes.polymsh_extracted3_SUB2_INT_Cuciture_0.geometry} material={materials.INT_Cuciture} />
          <mesh
            geometry={nodes.polymsh_extracted3_SUB3_INT_Pelle_Plasticata_0.geometry}
            material={materials.INT_Pelle_Plasticata}
          />
          <mesh
            geometry={nodes.polymsh_extracted3_SUB4_INT_Plastica_Scuro_0.geometry}
            material={materials.INT_Plastica_Scuro}
          />
          <mesh geometry={nodes.polymsh_extracted3_SUB5_INT_Decals_NM_0.geometry} material={materials.INT_Decals_NM} />
          <mesh
            geometry={nodes.polymsh_extracted3_SUB6_INT_LOGO_Volante_0.geometry}
            material={materials.INT_LOGO_Volante}
          />
          <mesh geometry={nodes.polymsh_extracted3_SUB7_INT_Decals_0.geometry} material={materials.INT_Decals} />
        </group>
        <mesh geometry={nodes.CINTURE_OFF_SUB0_INT_Cinture_0.geometry} material={materials.INT_Cinture} />
        <mesh
          geometry={nodes.CINTURE_OFF_SUB1_INT_Plastica_Grigia_0.geometry}
          material={materials.INT_Plastica_Grigia}
        />
        <mesh geometry={nodes.CINTURE_OFF_SUB2_INT_Cromato_0.geometry} material={materials.INT_Cromato} />
        <mesh
          geometry={nodes.CINTURE_ON_SUB1_INT_Plastica_Grigia_0.geometry}
          material={materials.INT_Plastica_Grigia}
        />
        <mesh geometry={nodes.CINTURE_ON_SUB2_INT_Cromato_0.geometry} material={materials.INT_Cromato} />
        <mesh geometry={nodes.cube_SUB0_INT_Plastica_Grigia_0.geometry} material={materials.INT_Plastica_Grigia} />
        <mesh geometry={nodes.cube_SUB1_INT_Navigatore_0.geometry} material={materials.INT_Navigatore} />
        <mesh geometry={nodes.cube_SUB10_INT_Pelle_Plasticata_0.geometry} material={materials.INT_Pelle_Plasticata} />
        <mesh geometry={nodes.cube_SUB11_INT_FlatBlack_0.geometry} material={materials.INT_FlatBlack} />
        <mesh geometry={nodes.cube_SUB12_INT_Metallo_semiopaco_0.geometry} material={materials.INT_Metallo_semiopaco} />
        <mesh geometry={nodes.cube_SUB13_INT_Speakers_0.geometry} material={materials.INT_Speakers} />
        <mesh geometry={nodes.cube_SUB14_INT_display_0.geometry} material={materials.INT_display} />
        <mesh
          geometry={nodes.cube_SUB15_INT_Plastica_ROSSA_Ref_0.geometry}
          material={materials.INT_Plastica_ROSSA_Ref}
        />
        <mesh geometry={nodes.cube_SUB16_INT_Carpet_0.geometry} material={materials.INT_Carpet} />
        <mesh geometry={nodes.cube_SUB17_INT_Speakers_GRID_0.geometry} material={materials.INT_Speakers_GRID} />
        <mesh geometry={nodes.cube_SUB18_INT_Tessuto1_0.geometry} material={materials.INT_Tessuto1} />
        <mesh geometry={nodes.cube_SUB19_Carpaint_Main_0.geometry} material={materials.Carpaint_Main_0} />
        <mesh geometry={nodes.cube_SUB2_INT_Vetro_0.geometry} material={materials['INT_Vetro.001']} />
        <mesh geometry={nodes.cube_SUB20_INT_Gomma_0.geometry} material={materials.INT_Gomma} />
        <mesh geometry={nodes.cube_SUB21_INT_Pedali_NM_0.geometry} material={materials.INT_Pedali_NM} />
        <mesh geometry={nodes.cube_SUB22_Mirror_0.geometry} material={materials.Mirror} />
        <mesh geometry={nodes.cube_SUB23_INT_LOGHI_metallici_0.geometry} material={materials.INT_LOGHI_metallici} />
        <mesh geometry={nodes.cube_SUB24_INT_LOGHI_Plastica_0.geometry} material={materials.INT_LOGHI_Plastica} />
        <mesh geometry={nodes.cube_SUB25_INT_Tessuto2_0.geometry} material={materials.INT_Tessuto2} />
        <mesh geometry={nodes.cube_SUB26_INT_Plastica_ROSSA_0.geometry} material={materials.INT_Plastica_ROSSA} />
        <mesh geometry={nodes.cube_SUB3_INT_Decals_0.geometry} material={materials.INT_Decals} />
        <mesh geometry={nodes.cube_SUB4_INT_Plastica_Scuro_0.geometry} material={materials.INT_Plastica_Scuro} />
        <mesh geometry={nodes.cube_SUB5_INT_CARBON_fine_0.geometry} material={materials.INT_CARBON_fine} />
        <mesh geometry={nodes.cube_SUB6_INT_alluminio_0.geometry} material={materials.INT_alluminio} />
        <mesh geometry={nodes.cube_SUB7_INT_Plastica_NERA_Ref_0.geometry} material={materials.INT_Plastica_NERA_Ref} />
        <mesh geometry={nodes.cube_SUB8_INT_Cromato_0.geometry} material={materials.INT_Cromato} />
        <mesh geometry={nodes.cube_SUB9_INT_Pelle_Morbida_0.geometry} material={materials.INT_Pelle_Morbida} />
        <mesh geometry={nodes.FUEL_LED_1_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.FUEL_LED_2_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.FUEL_LED_3_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.FUEL_LED_4_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.FUEL_LED_5_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.GEO_Display_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.limit1_2_INT_LED_0.geometry} material={materials.INT_LED} />
        <mesh geometry={nodes.limit2_2_INT_LED_0.geometry} material={materials.INT_LED} />
        <mesh geometry={nodes.limit3_2_INT_LED_0.geometry} material={materials.INT_LED} />
        <mesh geometry={nodes.LOGHI_sedili_2_INT_LOGO_Sedile_0.geometry} material={materials.INT_LOGO_Sedile} />
        <mesh geometry={nodes.polymsh72_SUB0_INT_Plastica_Grigia_0.geometry} material={materials.INT_Plastica_Grigia} />
        <mesh geometry={nodes.polymsh72_SUB1_INT_Cromato_0.geometry} material={materials.INT_Cromato} />
        <mesh geometry={nodes.polymsh_detached_2_INT_Cinture_0.geometry} material={materials.INT_Cinture} />
        <mesh geometry={nodes.polymsh_detached39_2_INT_Cuciture_0.geometry} material={materials.INT_Cuciture} />
        <group position={[0, 42.774, 35.323]}>
          <group position={[0, 4.424, -0.397]}>
            <mesh
              geometry={nodes.polymsh_extracted_SUB0_INT_Decals_0.geometry}
              material={materials.INT_Decals}
              position={[0.636, 0.556, -0.093]}
            />
            <mesh
              geometry={nodes.polymsh_extracted_SUB1_INT_Asta_Cambio_0.geometry}
              material={materials.INT_Asta_Cambio}
            />
            <mesh
              geometry={nodes.polymsh_extracted_SUB2_INT_Plastica_Scuro_0.geometry}
              material={materials.INT_Plastica_Scuro}
            />
            <mesh geometry={nodes.polymsh_extracted_SUB3_INT_Cromato_0.geometry} material={materials.INT_Cromato} />
          </group>
        </group>
        <mesh geometry={nodes.guaina_cambio_SUB0_INT_Cuciture_RIG_0.geometry} material={materials.INT_Cuciture_RIG} />
        <mesh
          geometry={nodes.guaina_cambio_SUB1_INT_Pelle_Morbida_skin_0.geometry}
          material={materials.INT_Pelle_Morbida_skin}
        />
        <mesh geometry={nodes.TAG_WATER_0_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.TAG_WATER_1_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.TAG_WATER_10_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.TAG_WATER_11_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.TAG_WATER_2_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.TAG_WATER_3_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.TAG_WATER_4_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.TAG_WATER_5_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.TAG_WATER_6_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.TAG_WATER_7_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.TAG_WATER_8_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.TAG_WATER_9_2_INT_display_0.geometry} material={materials.INT_display} />
        <mesh geometry={nodes.GEO_Cockpit_SUB1_Carpaint_Main_0.geometry} material={materials.Carpaint_Main_0} />
        <mesh geometry={nodes.front_light1_2_front_light1_0.geometry} material={materials.front_light1} />
        <mesh geometry={nodes.front_light2_2_INT_Glass_side_0.geometry} material={materials.INT_Glass_side} />
        <mesh geometry={nodes.front_light3_2_front_light1_0.geometry} material={materials.front_light1} />
        <mesh geometry={nodes.g_BODY_EXT_SUB0_Details_0.geometry} material={materials.Details} />
        <mesh geometry={nodes.g_BODY_EXT_SUB1_Plastic_Black_0.geometry} material={materials.Plastic_Black} />
        <mesh
          geometry={nodes.g_BODY_EXT_SUB10_Lotus_Performance_Logo_0.geometry}
          material={materials.Lotus_Performance_Logo}
        />
        <mesh geometry={nodes.g_BODY_EXT_SUB2_Engine_Cover_0.geometry} material={materials.Engine_Cover} />
        <mesh geometry={nodes.g_BODY_EXT_SUB3_Glass_0.geometry} material={materials.Glass} />
        <mesh geometry={nodes.g_BODY_EXT_SUB3_1_INT_Glass_side_0.geometry} material={materials.INT_Glass_side} />
        <mesh geometry={nodes.g_BODY_EXT_SUB4_Rubber_Black_0.geometry} material={materials.Rubber_Black} />
        <mesh geometry={nodes.g_BODY_EXT_SUB5_Chrome_0.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.g_BODY_EXT_SUB6_Grids_0.geometry} material={materials.Grids} />
        <mesh geometry={nodes.g_BODY_EXT_SUB7_Carpaint_Black_0.geometry} material={materials.Carpaint_Black} />
        <mesh geometry={nodes.g_BODY_EXT_SUB8_INT_Glass_side_0.geometry} material={materials.INT_Glass_side} />
        <mesh geometry={nodes.g_BODY_EXT_SUB9_Carpaint_Main_0.geometry} material={materials.Carpaint_Main_0} />
        <mesh geometry={nodes.polymsh_detached32_2_Glass_0.geometry} material={materials.Glass} />
        <mesh geometry={nodes.REAR_LIGHT_1_2_brake_light_0.geometry} material={materials.brake_light} />
        <mesh geometry={nodes.REAR_LIGHT_2_2_brake_light_0.geometry} material={materials.brake_light} />
        <mesh geometry={nodes.retro_light_2_brake_light_0.geometry} material={materials.brake_light} />
      </group>
    </group>
  )
}

useGLTF.preload('/model4.glb')
