/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 cc.glb -t 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useRecoilState } from "recoil";
import {
  AtomBumperColors,
  AtomGearColors,
  AtomTireWheelColors,
} from "../atoms/atoms";

type GLTFResult = GLTF & {
  nodes: {
    CAR_chrome_2_CAR_chrome2_0: THREE.Mesh;
    CAR_guarnizioni_2_CAR_guarnizioni_0: THREE.Mesh;
    CAR_lights_2_CAR_lights_0: THREE.Mesh;
    CAR_lights_back_2_CAR_lights_back6_0: THREE.Mesh;
    CINTURE_ON_SUB1_INT_black_plastic5_0: THREE.Mesh;
    CINTURE_ON_SUB2_INT_chrome_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB0_CAR_black_plastic2_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB1_CAR_dark_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB10_INT_red_plastic2_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB11_INT_controlpanel_D_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB12_INT_spotted_plastic3_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB13_INT_white_plastic2_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB14_INT_black_matte_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB15_INT_chrome1_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB16_INT_speakers_cover1_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB17_INT_seams_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB2_INT_grey_plastic_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB3_INT_speakers_cover2_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB4_INT_aluminium4_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB5_INT_black_plastic6_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB6_INT_velvet_black_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB7_INT_belt_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB8_INT_dashboard_0: THREE.Mesh;
    COCKPIT_HR_mesh_SUB9_INT_glass_0: THREE.Mesh;
    FUEL_LED_0_2_INT_dashboard1_0: THREE.Mesh;
    FUEL_LED_1_2_INT_dashboard2_0: THREE.Mesh;
    FUEL_LED_2_2_INT_dashboard3_0: THREE.Mesh;
    FUEL_LED_3_2_INT_dashboard4_0: THREE.Mesh;
    FUEL_LED_4_2_INT_dashboard5_0: THREE.Mesh;
    GEO_Guaina_cambio_2_INT_soft_leather_Skinned_0: THREE.Mesh;
    GEO_LCD_2_INT_dashboard6_0: THREE.Mesh;
    GEO_Sedili_standard_SUB0_INT_speakers_cover3_0: THREE.Mesh;
    GEO_Sedili_standard_SUB1_INT_velvet_black1_0: THREE.Mesh;
    GEO_Sedili_standard_SUB2_INT_spotted_plastic4_0: THREE.Mesh;
    GEO_Sedili_standard_SUB3_INT_black_plastic7_0: THREE.Mesh;
    GEO_Sedili_standard_SUB4_INT_seams1_0: THREE.Mesh;
    GEO_Sedili_standard_SUB5_INT_seat_logo_0: THREE.Mesh;
    INT_Vetro_cockpit_2_CAR_glass2_0: THREE.Mesh;
    LED_Limiter_1_2_Limiter_0: THREE.Mesh;
    LED_Limiter_2_2_Limiter2_0: THREE.Mesh;
    LED_Limiter_3_2_Limiter1_0: THREE.Mesh;
    polymsh_detached4_2_INT_Vetro_0: THREE.Mesh;
    RPM_INDICATOR_mesh_SUB0_INT_red_plastic_0: THREE.Mesh;
    RPM_INDICATOR_mesh_SUB1_INT_black_plastic2_0: THREE.Mesh;
    GEO_manopolo_cambio_2_INT_aluminium3_0: THREE.Mesh;
    SPEED_INDICATOR_mesh_SUB0_INT_red_plastic1_0: THREE.Mesh;
    SPEED_INDICATOR_mesh_SUB1_INT_black_plastic3_0: THREE.Mesh;
    STEERING_HR_mesh_SUB0_INT_spotted_plastic2_0: THREE.Mesh;
    STEERING_HR_mesh_SUB1_INT_aluminium2_0: THREE.Mesh;
    STEERING_HR_mesh_SUB2_INT_black_plastic4_0: THREE.Mesh;
    STEERING_HR_mesh_SUB3_INT_textured_0: THREE.Mesh;
    STEERING_HR_mesh_SUB4_INT_speakers_cover_0: THREE.Mesh;
    DISCBRAKE_RF_mesh1_2_CAR_disk_0: THREE.Mesh;
    DISCBRAKE_LR_mesh_2_CAR_disk3_0: THREE.Mesh;
    DISCBRAKE_RF_mesh_2_CAR_disk1_0: THREE.Mesh;
    DISCBRAKE_RR_mesh_2_CAR_disk2_0: THREE.Mesh;
    L_door_H1_SUB0_INT_black_plastic_0: THREE.Mesh;
    L_door_H1_SUB1_CAR_chassis_0: THREE.Mesh;
    L_door_H1_SUB2_INT_aluminium_0: THREE.Mesh;
    L_door_H1_SUB3_INT_spotted_plastic_0: THREE.Mesh;
    L_door_H1_SUB4_INT_side_light_0: THREE.Mesh;
    L_door_H1_SUB5_INT_white_plastic_0: THREE.Mesh;
    L_door_H1_SUB6_INT_glass_side_0: THREE.Mesh;
    GEO_Door_L_SUB0_CAR_mirrors_0: THREE.Mesh;
    GEO_Door_L_SUB1_CAR_bottom_0: THREE.Mesh;
    GEO_Door_L_SUB2_CAR_black_plastic_0: THREE.Mesh;
    GEO_Door_L_SUB3_CAR_glass_0: THREE.Mesh;
    GEO_Door_L_SUB4_CAR_chassis1_0: THREE.Mesh;
    GEO_Door_L_SUB5_CAR_chrome_0: THREE.Mesh;
    R_door_H_SUB0_INT_black_plastic1_0: THREE.Mesh;
    R_door_H_SUB1_CAR_chassis2_0: THREE.Mesh;
    R_door_H_SUB2_INT_aluminium1_0: THREE.Mesh;
    R_door_H_SUB3_INT_spotted_plastic1_0: THREE.Mesh;
    R_door_H_SUB4_INT_side_light1_0: THREE.Mesh;
    R_door_H_SUB5_INT_white_plastic1_0: THREE.Mesh;
    R_door_H_SUB6_INT_glass_side1_0: THREE.Mesh;
    GEO_Door_R_SUB0_CAR_glass1_0: THREE.Mesh;
    GEO_Door_R_SUB1_CAR_black_plastic1_0: THREE.Mesh;
    GEO_Door_R_SUB2_CAR_mirrors1_0: THREE.Mesh;
    GEO_Door_R_SUB3_CAR_bottom1_0: THREE.Mesh;
    GEO_Door_R_SUB4_CAR_chassis3_0: THREE.Mesh;
    GEO_Door_R_SUB5_CAR_chrome1_0: THREE.Mesh;
    polymsh_detached16_SUB0_CAR_chassis6_0: THREE.Mesh;
    polymsh_detached16_SUB1_CAR_mechanics_AT6_0: THREE.Mesh;
    F_lights_abbaglianti_2_CAR_lights2_0: THREE.Mesh;
    F_lights_anabbaglianti_2_CAR_lights1_0: THREE.Mesh;
    LIGHT_Default_2_CAR_lights3_0: THREE.Mesh;
    LIGHT_Extra_2_CAR_lights4_0: THREE.Mesh;
    GEO_frontbumper_SUB0_CAR_Grid_Exagon1_0: THREE.Mesh;
    GEO_frontbumper_SUB1_CAR_black_plastic4_0: THREE.Mesh;
    GEO_frontbumper_SUB10_CAR_lights5_0: THREE.Mesh;
    GEO_frontbumper_SUB2_CAR_glass4_0: THREE.Mesh;
    GEO_frontbumper_SUB3_CAR_glass_black1_0: THREE.Mesh;
    GEO_frontbumper_SUB4_CAR_chassis5_0: THREE.Mesh;
    GEO_frontbumper_SUB5_CAR_mechanics_AT5_0: THREE.Mesh;
    GEO_frontbumper_SUB6_CAR_LOGO_elise4_0: THREE.Mesh;
    GEO_frontbumper_SUB7_CAR_Decals_Alfa1_0: THREE.Mesh;
    GEO_frontbumper_SUB8_CAR_Plastica_OCC1_0: THREE.Mesh;
    GEO_frontbumper_SUB9_CAR_bottom5_0: THREE.Mesh;
    INT_Vetro_motore_2_CAR_glass3_0: THREE.Mesh;
    polymsh_detached19_SUB0_CAR_chassis7_0: THREE.Mesh;
    polymsh_detached19_SUB1_CAR_Grid_Exagon2_0: THREE.Mesh;
    polymsh_detached19_SUB2_CAR_bottom6_0: THREE.Mesh;
    polymsh_detached15_SUB0_CAR_chassis8_0: THREE.Mesh;
    polymsh_detached15_SUB1_CAR_mechanics_AT7_0: THREE.Mesh;
    polymsh8_SUB0_CAR_chassis4_0: THREE.Mesh;
    polymsh8_SUB1_CAR_engine_0: THREE.Mesh;
    polymsh8_SUB10_CAR_mechanics_AT4_0: THREE.Mesh;
    polymsh8_SUB11_CAR_Carbon_0: THREE.Mesh;
    polymsh8_SUB12_CAR_grid_engine_0: THREE.Mesh;
    polymsh8_SUB13_CAR_Griglia_RETRO_0: THREE.Mesh;
    polymsh8_SUB14_CAR_Grid_Exagon_0: THREE.Mesh;
    polymsh8_SUB15_CAR_exhaust_0: THREE.Mesh;
    polymsh8_SUB2_CAR_black_plastic3_0: THREE.Mesh;
    polymsh8_SUB3_CAR_Decals_Base_0: THREE.Mesh;
    polymsh8_SUB5_CAR_glass_black_0: THREE.Mesh;
    polymsh8_SUB6_CAR_bottom2_0: THREE.Mesh;
    polymsh8_SUB7_CAR_Decals_Alfa_0: THREE.Mesh;
    polymsh8_SUB8_CAR_mirrors2_0: THREE.Mesh;
    polymsh8_SUB9_CAR_Plastica_OCC_0: THREE.Mesh;
    polymsh_detached13_2_CAR_bottom4_0: THREE.Mesh;
    polymsh_detached18_2_CAR_bottom3_0: THREE.Mesh;
    LIGHT_ARROW_REAR_2_CAR_lights_back2_0: THREE.Mesh;
    LIGHT_BRAKE_2_CAR_lights_back_0: THREE.Mesh;
    LIGHT_EXTERNAL_2_CAR_lights_back5_0: THREE.Mesh;
    LIGHT_REAR_RETRO_2_CAR_lights_back3_0: THREE.Mesh;
    LIGHTS_Central_BRAKE_2_CAR_lights_back4_0: THREE.Mesh;
    LIGHTS_REAR_2_CAR_lights_back1_0: THREE.Mesh;
    SUSP_LF_mesh_2_CAR_mechanics_AT1_0: THREE.Mesh;
    SUSP_LR_mesh_2_CAR_mechanics_AT_0: THREE.Mesh;
    SUSP_RF_mesh_2_CAR_mechanics_AT3_0: THREE.Mesh;
    SUSP_RR_mesh_2_CAR_mechanics_AT2_0: THREE.Mesh;
    TYRE_LF_1_battistrada2_0: THREE.Mesh;
    TYRE_LF_1_CAR_LOGO_elise2_0: THREE.Mesh;
    TYRE_LF_1_CAR_RIM2_0: THREE.Mesh;
    TYRE_LR_1_battistrada_0: THREE.Mesh;
    TYRE_LR_1_CAR_LOGO_elise_0: THREE.Mesh;
    TYRE_LR_1_CAR_RIM_0: THREE.Mesh;
    TYRE_RF_1_battistrada1_0: THREE.Mesh;
    TYRE_RF_1_CAR_LOGO_elise1_0: THREE.Mesh;
    TYRE_RF_1_CAR_RIM1_0: THREE.Mesh;
    TYRE_RR_1_battistrada3_0: THREE.Mesh;
    TYRE_RR_1_CAR_LOGO_elise3_0: THREE.Mesh;
    TYRE_RR_1_CAR_RIM3_0: THREE.Mesh;
    GEO_wiper_2_CAR_black_plastic5_0: THREE.Mesh;
    GEO_Wiper_Brush_2_CAR_black_plastic6_0: THREE.Mesh;
  };
  materials: {
    ["CAR_chrome.1"]: THREE.MeshStandardMaterial;
    CAR_guarnizioni: THREE.MeshStandardMaterial;
    CAR_lights_2: THREE.MeshStandardMaterial;
    ["CAR_lights_back.1_0"]: THREE.MeshStandardMaterial;
    ["INT_black_plastic.4"]: THREE.MeshStandardMaterial;
    INT_chrome: THREE.MeshStandardMaterial;
    ["CAR_black_plastic.5"]: THREE.MeshStandardMaterial;
    ["INT_white_plastic.2_0"]: THREE.MeshStandardMaterial;
    ["INT_aluminium.1_0"]: THREE.MeshStandardMaterial;
    INT_controlpanel_D: THREE.MeshStandardMaterial;
    ["INT_spotted_plastic.4_0"]: THREE.MeshStandardMaterial;
    ["INT_white_plastic.2"]: THREE.MeshStandardMaterial;
    INT_black_matte: THREE.MeshStandardMaterial;
    ["INT_aluminium.1_1"]: THREE.MeshStandardMaterial;
    ["INT_seams.1"]: THREE.MeshStandardMaterial;
    INT_grey_plastic: THREE.MeshStandardMaterial;
    ["INT_aluminium.1_2"]: THREE.MeshStandardMaterial;
    ["INT_aluminium.1"]: THREE.MeshStandardMaterial;
    INT_velvet_black: THREE.MeshStandardMaterial;
    INT_belt: THREE.MeshStandardMaterial;
    ["INT_dashboard.3"]: THREE.MeshStandardMaterial;
    INT_glass: THREE.MeshStandardMaterial;
    INT_soft_leather_Skinned: THREE.MeshStandardMaterial;
    ["INT_spotted_plastic.4"]: THREE.MeshStandardMaterial;
    INT_seat_logo: THREE.MeshStandardMaterial;
    CAR_lights_0: THREE.MeshStandardMaterial;
    Limiter: THREE.MeshStandardMaterial;
    INT_Vetro: THREE.MeshStandardMaterial;
    ["CAR_lights_back.1"]: THREE.MeshStandardMaterial;
    CAR_disk: THREE.MeshStandardMaterial;
    ["CAR_chassis.5"]: THREE.MeshStandardMaterial;
    ["INT_side_light.1"]: THREE.MeshStandardMaterial;
    INT_glass_side: THREE.MeshStandardMaterial;
    CAR_lights: THREE.MeshStandardMaterial;
    CAR_bottom: THREE.MeshStandardMaterial;
    ["CAR_mechanics_AT.4"]: THREE.MeshStandardMaterial;
    ["CAR_Grid_Exagon.2"]: THREE.MeshStandardMaterial;
    CAR_lights_1: THREE.MeshStandardMaterial;
    ["CAR_LOGO_elise.2"]: THREE.MeshStandardMaterial;
    ["CAR_Decals_Alfa.1"]: THREE.MeshStandardMaterial;
    CAR_Plastica_OCC: THREE.MeshStandardMaterial;
    CAR_engine: THREE.MeshStandardMaterial;
    CAR_Carbon: THREE.MeshStandardMaterial;
    CAR_grid_engine: THREE.MeshStandardMaterial;
    CAR_Griglia_RETRO: THREE.MeshStandardMaterial;
    CAR_exhaust: THREE.MeshStandardMaterial;
    ["CAR_mechanics_AT.4_0"]: THREE.MeshStandardMaterial;
    battistrada: THREE.MeshStandardMaterial;
    ["CAR_RIM.3"]: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model3(props: JSX.IntrinsicElements["group"]) {
  const [bumperColors, setBumperColors] = useRecoilState(AtomBumperColors);
  const [gearColors, setGearColors] = useRecoilState(AtomGearColors);
  const [tireWheelColors, setTireWheelColors] =
    useRecoilState(AtomTireWheelColors);

  const { nodes, materials } = useGLTF("/model3.glb") as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[75.335, 29.897, 111.094]}>
          <mesh
            geometry={nodes.DISCBRAKE_RF_mesh1_2_CAR_disk_0.geometry}
            material={materials.CAR_disk}
            position={[-12.332, 0, 0]}
          >
            {gearColors !== "base" && (
              <meshPhysicalMaterial
                metalness={0.5}
                roughness={0.3}
                ior={1.5}
                color={new THREE.Color(gearColors)}
              />
            )}
          </mesh>
        </group>

        <group position={[69.294, 31.552, -119.596]}>
          <mesh
            geometry={nodes.DISCBRAKE_LR_mesh_2_CAR_disk3_0.geometry}
            material={materials.CAR_disk}
            position={[-13.691, 0, 0]}
          >
            {gearColors !== "base" && (
              <meshPhysicalMaterial
                metalness={0.5}
                roughness={0.3}
                ior={1.5}
                color={new THREE.Color(gearColors)}
              />
            )}
          </mesh>
        </group>
        <group position={[-75.334, 29.897, 111.094]}>
          <mesh
            geometry={nodes.DISCBRAKE_RF_mesh_2_CAR_disk1_0.geometry}
            material={materials.CAR_disk}
            position={[12.331, 0, 0]}
          >
            {gearColors !== "base" && (
              <meshPhysicalMaterial
                metalness={0.5}
                roughness={0.3}
                ior={1.5}
                color={new THREE.Color(gearColors)}
              />
            )}
          </mesh>
        </group>
        <group position={[-69.294, 31.552, -119.596]}>
          <mesh
            geometry={nodes.DISCBRAKE_RR_mesh_2_CAR_disk2_0.geometry}
            material={materials.CAR_disk}
            position={[13.691, 0, 0]}
          >
            {gearColors !== "base" && (
              <meshPhysicalMaterial
                metalness={0.5}
                roughness={0.3}
                ior={1.5}
                color={new THREE.Color(gearColors)}
              />
            )}
          </mesh>
        </group>
        <group position={[73.699, 57.831, 61.228]}>
          <group position={[-73.699, -57.831, -61.228]}>
            <mesh
              geometry={nodes.GEO_Door_L_SUB0_CAR_mirrors_0.geometry}
              material={materials.CAR_lights}
            />
            <mesh
              geometry={nodes.GEO_Door_L_SUB1_CAR_bottom_0.geometry}
              material={materials.CAR_bottom}
            />
            <mesh
              geometry={nodes.GEO_Door_L_SUB2_CAR_black_plastic_0.geometry}
              material={materials["CAR_black_plastic.5"]}
            />
            <mesh
              geometry={nodes.GEO_Door_L_SUB3_CAR_glass_0.geometry}
              material={materials.CAR_lights_0}
            />
            <mesh
              geometry={nodes.GEO_Door_L_SUB4_CAR_chassis1_0.geometry}
              material={materials["CAR_chassis.5"]}
            >
              {bumperColors !== "base" && (
                <meshPhysicalMaterial
                  metalness={0.5}
                  roughness={0.3}
                  ior={1.5}
                  color={new THREE.Color(bumperColors)}
                />
              )}
            </mesh>
            <mesh
              geometry={nodes.GEO_Door_L_SUB5_CAR_chrome_0.geometry}
              material={materials["CAR_chrome.1"]}
            />
          </group>
          <group position={[-73.699, -57.831, -61.228]}>
            <mesh
              geometry={nodes.L_door_H1_SUB0_INT_black_plastic_0.geometry}
              material={materials["INT_black_plastic.4"]}
            >
              {bumperColors !== "base" && (
                <meshPhysicalMaterial
                  metalness={0.5}
                  roughness={0.3}
                  ior={1.5}
                  color={new THREE.Color(bumperColors)}
                />
              )}
            </mesh>
            <mesh
              geometry={nodes.L_door_H1_SUB1_CAR_chassis_0.geometry}
              material={materials["CAR_chassis.5"]}
            >
              {bumperColors !== "base" && (
                <meshPhysicalMaterial
                  metalness={0.5}
                  roughness={0.3}
                  ior={1.5}
                  color={new THREE.Color(bumperColors)}
                />
              )}
            </mesh>
            <mesh
              geometry={nodes.L_door_H1_SUB2_INT_aluminium_0.geometry}
              material={materials["INT_aluminium.1"]}
            />
            <mesh
              geometry={nodes.L_door_H1_SUB3_INT_spotted_plastic_0.geometry}
              material={materials["INT_spotted_plastic.4"]}
            />
            <mesh
              geometry={nodes.L_door_H1_SUB4_INT_side_light_0.geometry}
              material={materials["INT_side_light.1"]}
            />
            <mesh
              geometry={nodes.L_door_H1_SUB5_INT_white_plastic_0.geometry}
              material={materials["INT_white_plastic.2"]}
            />
            <mesh
              geometry={nodes.L_door_H1_SUB6_INT_glass_side_0.geometry}
              material={materials.INT_glass_side}
            />
          </group>
        </group>
        <group position={[-73.704, 57.831, 61.228]}>
          <group position={[73.704, -57.831, -61.228]}>
            <mesh
              geometry={nodes.GEO_Door_R_SUB0_CAR_glass1_0.geometry}
              material={materials.CAR_lights_0}
            />
            <mesh
              geometry={nodes.GEO_Door_R_SUB1_CAR_black_plastic1_0.geometry}
              material={materials["CAR_black_plastic.5"]}
            />
            <mesh
              geometry={nodes.GEO_Door_R_SUB2_CAR_mirrors1_0.geometry}
              material={materials.CAR_lights}
            />
            <mesh
              geometry={nodes.GEO_Door_R_SUB3_CAR_bottom1_0.geometry}
              material={materials.CAR_bottom}
            />
            <mesh
              geometry={nodes.GEO_Door_R_SUB4_CAR_chassis3_0.geometry}
              material={materials["CAR_chassis.5"]}
            >
              {bumperColors !== "base" && (
                <meshPhysicalMaterial
                  metalness={0.5}
                  roughness={0.3}
                  ior={1.5}
                  color={new THREE.Color(bumperColors)}
                />
              )}
            </mesh>
            <mesh
              geometry={nodes.GEO_Door_R_SUB5_CAR_chrome1_0.geometry}
              material={materials["CAR_chrome.1"]}
            />
          </group>
          <group position={[73.704, -57.831, -61.228]}>
            <mesh
              geometry={nodes.R_door_H_SUB0_INT_black_plastic1_0.geometry}
              material={materials["INT_black_plastic.4"]}
            >
              {bumperColors !== "base" && (
                <meshPhysicalMaterial
                  metalness={0.5}
                  roughness={0.3}
                  ior={1.5}
                  color={new THREE.Color(bumperColors)}
                />
              )}
            </mesh>
            <mesh
              geometry={nodes.R_door_H_SUB1_CAR_chassis2_0.geometry}
              material={materials["CAR_chassis.5"]}
            >
              {bumperColors !== "base" && (
                <meshPhysicalMaterial
                  metalness={0.5}
                  roughness={0.3}
                  ior={1.5}
                  color={new THREE.Color(bumperColors)}
                />
              )}
            </mesh>
            <mesh
              geometry={nodes.R_door_H_SUB2_INT_aluminium1_0.geometry}
              material={materials["INT_aluminium.1"]}
            />
            <mesh
              geometry={nodes.R_door_H_SUB3_INT_spotted_plastic1_0.geometry}
              material={materials["INT_spotted_plastic.4"]}
            />
            <mesh
              geometry={nodes.R_door_H_SUB4_INT_side_light1_0.geometry}
              material={materials["INT_side_light.1"]}
            />
            <mesh
              geometry={nodes.R_door_H_SUB5_INT_white_plastic1_0.geometry}
              material={materials["INT_white_plastic.2"]}
            />
            <mesh
              geometry={nodes.R_door_H_SUB6_INT_glass_side1_0.geometry}
              material={materials.INT_glass_side}
            />
          </group>
        </group>
        <group position={[0, 14.359, -120.846]}>
          <mesh
            geometry={nodes.polymsh_detached16_SUB0_CAR_chassis6_0.geometry}
            material={materials["CAR_chassis.5"]}
          >
            {bumperColors !== "base" && (
              <meshPhysicalMaterial
                metalness={0.5}
                roughness={0.3}
                ior={1.5}
                color={new THREE.Color(bumperColors)}
              />
            )}
          </mesh>
          <mesh
            geometry={
              nodes.polymsh_detached16_SUB1_CAR_mechanics_AT6_0.geometry
            }
            material={materials["CAR_mechanics_AT.4"]}
          />
        </group>
        <group position={[0, 72.708, 48.025]}>
          <group position={[0, -72.708, -48.025]}>
            <mesh
              geometry={nodes.GEO_frontbumper_SUB0_CAR_Grid_Exagon1_0.geometry}
              material={materials["CAR_Grid_Exagon.2"]}
            />
            <mesh
              geometry={
                nodes.GEO_frontbumper_SUB1_CAR_black_plastic4_0.geometry
              }
              material={materials["CAR_black_plastic.5"]}
            />
            <mesh
              geometry={nodes.GEO_frontbumper_SUB10_CAR_lights5_0.geometry}
              material={materials.CAR_lights_2}
            />
            <mesh
              geometry={nodes.GEO_frontbumper_SUB2_CAR_glass4_0.geometry}
              material={materials.CAR_lights_0}
            />
            <mesh
              geometry={nodes.GEO_frontbumper_SUB3_CAR_glass_black1_0.geometry}
              material={materials.CAR_lights_1}
            />
            <mesh
              geometry={nodes.GEO_frontbumper_SUB4_CAR_chassis5_0.geometry}
              material={materials["CAR_chassis.5"]}
            >
              {bumperColors !== "base" && (
                <meshPhysicalMaterial
                  metalness={0.5}
                  roughness={0.3}
                  ior={1.5}
                  color={new THREE.Color(bumperColors)}
                />
              )}
            </mesh>

            <mesh
              geometry={nodes.GEO_frontbumper_SUB5_CAR_mechanics_AT5_0.geometry}
              material={materials["CAR_mechanics_AT.4"]}
            />
            <mesh
              geometry={nodes.GEO_frontbumper_SUB6_CAR_LOGO_elise4_0.geometry}
              material={materials["CAR_LOGO_elise.2"]}
            />
            <mesh
              geometry={nodes.GEO_frontbumper_SUB7_CAR_Decals_Alfa1_0.geometry}
              material={materials["CAR_Decals_Alfa.1"]}
            />
            <mesh
              geometry={nodes.GEO_frontbumper_SUB8_CAR_Plastica_OCC1_0.geometry}
              material={materials.CAR_Plastica_OCC}
            />
            <mesh
              geometry={nodes.GEO_frontbumper_SUB9_CAR_bottom5_0.geometry}
              material={materials.CAR_bottom}
            />
          </group>
          <mesh
            geometry={nodes.F_lights_abbaglianti_2_CAR_lights2_0.geometry}
            material={materials.CAR_lights_2}
          />
          <mesh
            geometry={nodes.F_lights_anabbaglianti_2_CAR_lights1_0.geometry}
            material={materials.CAR_lights_2}
          />
          <mesh
            geometry={nodes.LIGHT_Default_2_CAR_lights3_0.geometry}
            material={materials.CAR_lights_2}
          />
          <mesh
            geometry={nodes.LIGHT_Extra_2_CAR_lights4_0.geometry}
            material={materials.CAR_lights_2}
          />
        </group>
        <mesh
          geometry={nodes.INT_Vetro_motore_2_CAR_glass3_0.geometry}
          material={materials.CAR_lights_0}
          position={[0, 0, -0.255]}
        />
        <group position={[0, 104.202, -58.57]}>
          <group position={[0, -16.876, -96.741]}>
            <mesh
              geometry={nodes.polymsh_detached15_SUB0_CAR_chassis8_0.geometry}
              material={materials["CAR_chassis.5"]}
            >
              {bumperColors !== "base" && (
                <meshPhysicalMaterial
                  metalness={0.5}
                  roughness={0.3}
                  ior={1.5}
                  color={new THREE.Color(bumperColors)}
                />
              )}
            </mesh>
            <mesh
              geometry={
                nodes.polymsh_detached15_SUB1_CAR_mechanics_AT7_0.geometry
              }
              material={materials["CAR_mechanics_AT.4"]}
            />
          </group>
          <mesh
            geometry={nodes.polymsh_detached19_SUB0_CAR_chassis7_0.geometry}
            material={materials["CAR_chassis.5"]}
          >
            {bumperColors !== "base" && (
              <meshPhysicalMaterial
                metalness={0.5}
                roughness={0.3}
                ior={1.5}
                color={new THREE.Color(bumperColors)}
              />
            )}
          </mesh>
          <mesh
            geometry={nodes.polymsh_detached19_SUB1_CAR_Grid_Exagon2_0.geometry}
            material={materials["CAR_Grid_Exagon.2"]}
          />
          <mesh
            geometry={nodes.polymsh_detached19_SUB2_CAR_bottom6_0.geometry}
            material={materials.CAR_bottom}
          />
        </group>
        <group position={[75.335, 29.897, 111.094]}>
          <mesh
            geometry={nodes.SUSP_LF_mesh_2_CAR_mechanics_AT1_0.geometry}
            material={materials["CAR_mechanics_AT.4"]}
            position={[-12.332, 0, 0]}
          >
            {gearColors !== "base" && (
              <meshPhysicalMaterial
                metalness={0.5}
                roughness={0.3}
                ior={1.5}
                color={new THREE.Color(gearColors)}
              />
            )}
          </mesh>
        </group>
        <group position={[69.294, 31.552, -119.596]}>
          <mesh
            geometry={nodes.SUSP_LR_mesh_2_CAR_mechanics_AT_0.geometry}
            material={materials["CAR_mechanics_AT.4"]}
            position={[-13.691, 0, 0]}
          >
            {gearColors !== "base" && (
              <meshPhysicalMaterial
                metalness={0.5}
                roughness={0.3}
                ior={1.5}
                color={new THREE.Color(gearColors)}
              />
            )}
          </mesh>
        </group>
        <group position={[-75.334, 29.897, 111.094]}>
          <mesh
            geometry={nodes.SUSP_RF_mesh_2_CAR_mechanics_AT3_0.geometry}
            material={materials["CAR_mechanics_AT.4"]}
            position={[12.331, 0, 0]}
          >
            {gearColors !== "base" && (
              <meshPhysicalMaterial
                metalness={0.5}
                roughness={0.3}
                ior={1.5}
                color={new THREE.Color(gearColors)}
              />
            )}
          </mesh>
        </group>
        <group position={[-69.294, 31.552, -119.596]}>
          <mesh
            geometry={nodes.SUSP_RR_mesh_2_CAR_mechanics_AT2_0.geometry}
            material={materials["CAR_mechanics_AT.4"]}
            position={[13.691, 0, 0]}
          >
            {gearColors !== "base" && (
              <meshPhysicalMaterial
                metalness={0.5}
                roughness={0.3}
                ior={1.5}
                color={new THREE.Color(gearColors)}
              />
            )}
          </mesh>
        </group>
        <group position={[75.335, 29.897, 111.094]}>
          <group position={[-1.366, 0.007, 0.012]}>
            <mesh
              geometry={nodes.TYRE_LF_1_battistrada2_0.geometry}
              material={materials.battistrada}
            />
            <mesh
              geometry={nodes.TYRE_LF_1_CAR_LOGO_elise2_0.geometry}
              material={materials["CAR_LOGO_elise.2"]}
            />
            <mesh
              geometry={nodes.TYRE_LF_1_CAR_RIM2_0.geometry}
              material={materials["CAR_RIM.3"]}
            >
              {tireWheelColors !== "base" && (
                <meshPhysicalMaterial
                  metalness={0.5}
                  roughness={0.3}
                  ior={1.5}
                  color={new THREE.Color(tireWheelColors)}
                />
              )}
            </mesh>
          </group>
        </group>
        <group position={[69.294, 31.552, -119.596]}>
          <group position={[0.828, 0.007, 0.012]}>
            <mesh
              geometry={nodes.TYRE_LR_1_battistrada_0.geometry}
              material={materials.battistrada}
            />
            <mesh
              geometry={nodes.TYRE_LR_1_CAR_LOGO_elise_0.geometry}
              material={materials["CAR_LOGO_elise.2"]}
            />
            <mesh
              geometry={nodes.TYRE_LR_1_CAR_RIM_0.geometry}
              material={materials["CAR_RIM.3"]}
            >
              {tireWheelColors !== "base" && (
                <meshPhysicalMaterial
                  metalness={0.5}
                  roughness={0.3}
                  ior={1.5}
                  color={new THREE.Color(tireWheelColors)}
                />
              )}
            </mesh>
          </group>
        </group>
        <group position={[-75.334, 29.897, 111.094]}>
          <group position={[1.365, 0.007, -0.012]}>
            <mesh
              geometry={nodes.TYRE_RF_1_battistrada1_0.geometry}
              material={materials.battistrada}
            />
            <mesh
              geometry={nodes.TYRE_RF_1_CAR_LOGO_elise1_0.geometry}
              material={materials["CAR_LOGO_elise.2"]}
            />
            <mesh
              geometry={nodes.TYRE_RF_1_CAR_RIM1_0.geometry}
              material={materials["CAR_RIM.3"]}
            >
              {tireWheelColors !== "base" && (
                <meshPhysicalMaterial
                  metalness={0.5}
                  roughness={0.3}
                  ior={1.5}
                  color={new THREE.Color(tireWheelColors)}
                />
              )}
            </mesh>
          </group>
        </group>
        <group position={[-69.294, 31.552, -119.596]}>
          <group position={[-0.828, 0.007, -0.012]}>
            <mesh
              geometry={nodes.TYRE_RR_1_battistrada3_0.geometry}
              material={materials.battistrada}
            />
            <mesh
              geometry={nodes.TYRE_RR_1_CAR_LOGO_elise3_0.geometry}
              material={materials["CAR_LOGO_elise.2"]}
            />
            <mesh
              geometry={nodes.TYRE_RR_1_CAR_RIM3_0.geometry}
              material={materials["CAR_RIM.3"]}
            >
              {tireWheelColors !== "base" && (
                <meshPhysicalMaterial
                  metalness={0.5}
                  roughness={0.3}
                  ior={1.5}
                  color={new THREE.Color(tireWheelColors)}
                />
              )}
            </mesh>
          </group>
        </group>
        <group
          position={[-0.03, 68.974, 96.455]}
          rotation={[-2.404, 0.547, 3.137]}
        >
          <mesh
            geometry={nodes.GEO_Wiper_Brush_2_CAR_black_plastic6_0.geometry}
            material={materials["CAR_black_plastic.5"]}
            position={[43.901, -5.017, -2.64]}
            rotation={[0, 0, -0.364]}
          />
          <mesh
            geometry={nodes.GEO_wiper_2_CAR_black_plastic5_0.geometry}
            material={materials["CAR_black_plastic.5"]}
          />
        </group>
        <mesh
          geometry={nodes.CAR_chrome_2_CAR_chrome2_0.geometry}
          material={materials["CAR_chrome.1"]}
        />
        <mesh
          geometry={nodes.CAR_guarnizioni_2_CAR_guarnizioni_0.geometry}
          material={materials.CAR_guarnizioni}
        />
        <mesh
          geometry={nodes.CAR_lights_2_CAR_lights_0.geometry}
          material={materials.CAR_lights_2}
        />
        <mesh
          geometry={nodes.CAR_lights_back_2_CAR_lights_back6_0.geometry}
          material={materials["CAR_lights_back.1_0"]}
        />
        <mesh
          geometry={nodes.FUEL_LED_0_2_INT_dashboard1_0.geometry}
          material={materials["INT_dashboard.3"]}
          position={[0, -0.044, 0]}
        />
        <group position={[30.229, 67.981, 43.405]}>
          <mesh
            geometry={nodes.RPM_INDICATOR_mesh_SUB0_INT_red_plastic_0.geometry}
            material={materials["INT_aluminium.1_0"]}
          />
          <mesh
            geometry={
              nodes.RPM_INDICATOR_mesh_SUB1_INT_black_plastic2_0.geometry
            }
            material={materials["INT_black_plastic.4"]}
          />
        </group>
        <group position={[-1.342, 35.716, 28.92]}>
          <mesh
            geometry={nodes.GEO_manopolo_cambio_2_INT_aluminium3_0.geometry}
            material={materials["INT_aluminium.1"]}
            position={[0, 2.192, 0]}
            rotation={[0, 0, -0.058]}
          />
        </group>
        <group position={[20.322, 68.162, 43.399]}>
          <mesh
            geometry={
              nodes.SPEED_INDICATOR_mesh_SUB0_INT_red_plastic1_0.geometry
            }
            material={materials["INT_aluminium.1_0"]}
          />
          <mesh
            geometry={
              nodes.SPEED_INDICATOR_mesh_SUB1_INT_black_plastic3_0.geometry
            }
            material={materials["INT_black_plastic.4"]}
          />
        </group>
        <group position={[25.201, 63.376, 24.588]} rotation={[0.279, 0, 0]}>
          <mesh
            geometry={
              nodes.STEERING_HR_mesh_SUB0_INT_spotted_plastic2_0.geometry
            }
            material={materials["INT_spotted_plastic.4"]}
          />
          <mesh
            geometry={nodes.STEERING_HR_mesh_SUB1_INT_aluminium2_0.geometry}
            material={materials["INT_aluminium.1"]}
          />
          <mesh
            geometry={nodes.STEERING_HR_mesh_SUB2_INT_black_plastic4_0.geometry}
            material={materials["INT_black_plastic.4"]}
          />
          <mesh
            geometry={nodes.STEERING_HR_mesh_SUB3_INT_textured_0.geometry}
            material={materials["CAR_lights_back.1"]}
          />
          <mesh
            geometry={nodes.STEERING_HR_mesh_SUB4_INT_speakers_cover_0.geometry}
            material={materials["INT_aluminium.1_1"]}
          />
        </group>
        <mesh
          geometry={nodes.CINTURE_ON_SUB1_INT_black_plastic5_0.geometry}
          material={materials["INT_black_plastic.4"]}
        />
        <mesh
          geometry={nodes.CINTURE_ON_SUB2_INT_chrome_0.geometry}
          material={materials.INT_chrome}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB0_CAR_black_plastic2_0.geometry}
          material={materials["CAR_black_plastic.5"]}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB1_CAR_dark_0.geometry}
          material={materials["INT_white_plastic.2_0"]}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB10_INT_red_plastic2_0.geometry}
          material={materials["INT_aluminium.1_0"]}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB11_INT_controlpanel_D_0.geometry}
          material={materials.INT_controlpanel_D}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB12_INT_spotted_plastic3_0.geometry}
          material={materials["INT_spotted_plastic.4_0"]}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB13_INT_white_plastic2_0.geometry}
          material={materials["INT_white_plastic.2"]}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB14_INT_black_matte_0.geometry}
          material={materials.INT_black_matte}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB15_INT_chrome1_0.geometry}
          material={materials.INT_chrome}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB16_INT_speakers_cover1_0.geometry}
          material={materials["INT_aluminium.1_1"]}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB17_INT_seams_0.geometry}
          material={materials["INT_seams.1"]}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB2_INT_grey_plastic_0.geometry}
          material={materials.INT_grey_plastic}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB3_INT_speakers_cover2_0.geometry}
          material={materials["INT_aluminium.1_2"]}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB4_INT_aluminium4_0.geometry}
          material={materials["INT_aluminium.1"]}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB5_INT_black_plastic6_0.geometry}
          material={materials["INT_black_plastic.4"]}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB6_INT_velvet_black_0.geometry}
          material={materials.INT_velvet_black}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB7_INT_belt_0.geometry}
          material={materials.INT_belt}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB8_INT_dashboard_0.geometry}
          material={materials["INT_dashboard.3"]}
        />
        <mesh
          geometry={nodes.COCKPIT_HR_mesh_SUB9_INT_glass_0.geometry}
          material={materials.INT_glass}
        />
        <mesh
          geometry={nodes.FUEL_LED_1_2_INT_dashboard2_0.geometry}
          material={materials["INT_dashboard.3"]}
        />
        <mesh
          geometry={nodes.FUEL_LED_2_2_INT_dashboard3_0.geometry}
          material={materials["INT_dashboard.3"]}
        />
        <mesh
          geometry={nodes.FUEL_LED_3_2_INT_dashboard4_0.geometry}
          material={materials["INT_dashboard.3"]}
        />
        <mesh
          geometry={nodes.FUEL_LED_4_2_INT_dashboard5_0.geometry}
          material={materials["INT_dashboard.3"]}
        />
        <mesh
          geometry={
            nodes.GEO_Guaina_cambio_2_INT_soft_leather_Skinned_0.geometry
          }
          material={materials.INT_soft_leather_Skinned}
        />
        <mesh
          geometry={nodes.GEO_LCD_2_INT_dashboard6_0.geometry}
          material={materials["INT_dashboard.3"]}
        />
        <mesh
          geometry={
            nodes.GEO_Sedili_standard_SUB0_INT_speakers_cover3_0.geometry
          }
          material={materials["INT_aluminium.1_1"]}
        />
        <mesh
          geometry={nodes.GEO_Sedili_standard_SUB1_INT_velvet_black1_0.geometry}
          material={materials.INT_velvet_black}
        />
        <mesh
          geometry={
            nodes.GEO_Sedili_standard_SUB2_INT_spotted_plastic4_0.geometry
          }
          material={materials["INT_spotted_plastic.4"]}
        />
        <mesh
          geometry={
            nodes.GEO_Sedili_standard_SUB3_INT_black_plastic7_0.geometry
          }
          material={materials["INT_black_plastic.4"]}
        />
        <mesh
          geometry={nodes.GEO_Sedili_standard_SUB4_INT_seams1_0.geometry}
          material={materials["INT_seams.1"]}
        />
        <mesh
          geometry={nodes.GEO_Sedili_standard_SUB5_INT_seat_logo_0.geometry}
          material={materials.INT_seat_logo}
        />
        <mesh
          geometry={nodes.INT_Vetro_cockpit_2_CAR_glass2_0.geometry}
          material={materials.CAR_lights_0}
        />
        <mesh
          geometry={nodes.LED_Limiter_1_2_Limiter_0.geometry}
          material={materials.Limiter}
        />
        <mesh
          geometry={nodes.LED_Limiter_2_2_Limiter2_0.geometry}
          material={materials.Limiter}
        />
        <mesh
          geometry={nodes.LED_Limiter_3_2_Limiter1_0.geometry}
          material={materials.Limiter}
        />
        <mesh
          geometry={nodes.polymsh_detached4_2_INT_Vetro_0.geometry}
          material={materials.INT_Vetro}
        />
        <mesh
          geometry={nodes.polymsh8_SUB0_CAR_chassis4_0.geometry}
          material={materials["CAR_chassis.5"]}
        >
          {bumperColors !== "base" && (
            <meshPhysicalMaterial
              metalness={0.5}
              roughness={0.3}
              ior={1.5}
              color={new THREE.Color(bumperColors)}
            />
          )}
        </mesh>
        <mesh
          geometry={nodes.polymsh8_SUB1_CAR_engine_0.geometry}
          material={materials.CAR_engine}
        />
        <mesh
          geometry={nodes.polymsh8_SUB10_CAR_mechanics_AT4_0.geometry}
          material={materials["CAR_mechanics_AT.4"]}
        />
        <mesh
          geometry={nodes.polymsh8_SUB11_CAR_Carbon_0.geometry}
          material={materials.CAR_Carbon}
        />
        <mesh
          geometry={nodes.polymsh8_SUB12_CAR_grid_engine_0.geometry}
          material={materials.CAR_grid_engine}
        />
        <mesh
          geometry={nodes.polymsh8_SUB13_CAR_Griglia_RETRO_0.geometry}
          material={materials.CAR_Griglia_RETRO}
        />
        <mesh
          geometry={nodes.polymsh8_SUB14_CAR_Grid_Exagon_0.geometry}
          material={materials["CAR_Grid_Exagon.2"]}
        />
        <mesh
          geometry={nodes.polymsh8_SUB15_CAR_exhaust_0.geometry}
          material={materials.CAR_exhaust}
        />
        <mesh
          geometry={nodes.polymsh8_SUB2_CAR_black_plastic3_0.geometry}
          material={materials["CAR_black_plastic.5"]}
        />
        <mesh
          geometry={nodes.polymsh8_SUB3_CAR_Decals_Base_0.geometry}
          material={materials["CAR_mechanics_AT.4_0"]}
        />
        <mesh
          geometry={nodes.polymsh8_SUB5_CAR_glass_black_0.geometry}
          material={materials.CAR_lights_1}
        />
        <mesh
          geometry={nodes.polymsh8_SUB6_CAR_bottom2_0.geometry}
          material={materials.CAR_bottom}
        />
        <mesh
          geometry={nodes.polymsh8_SUB7_CAR_Decals_Alfa_0.geometry}
          material={materials["CAR_Decals_Alfa.1"]}
        />
        <mesh
          geometry={nodes.polymsh8_SUB8_CAR_mirrors2_0.geometry}
          material={materials.CAR_lights}
        />
        <mesh
          geometry={nodes.polymsh8_SUB9_CAR_Plastica_OCC_0.geometry}
          material={materials.CAR_Plastica_OCC}
        />
        <mesh
          geometry={nodes.polymsh_detached13_2_CAR_bottom4_0.geometry}
          material={materials.CAR_bottom}
        />
        <mesh
          geometry={nodes.polymsh_detached18_2_CAR_bottom3_0.geometry}
          material={materials.CAR_bottom}
        />
        <mesh
          geometry={nodes.LIGHT_ARROW_REAR_2_CAR_lights_back2_0.geometry}
          material={materials["CAR_lights_back.1_0"]}
        />
        <mesh
          geometry={nodes.LIGHT_BRAKE_2_CAR_lights_back_0.geometry}
          material={materials["CAR_lights_back.1_0"]}
        />
        <mesh
          geometry={nodes.LIGHT_EXTERNAL_2_CAR_lights_back5_0.geometry}
          material={materials["CAR_lights_back.1_0"]}
        />
        <mesh
          geometry={nodes.LIGHT_REAR_RETRO_2_CAR_lights_back3_0.geometry}
          material={materials["CAR_lights_back.1_0"]}
        />
        <mesh
          geometry={nodes.LIGHTS_Central_BRAKE_2_CAR_lights_back4_0.geometry}
          material={materials["CAR_lights_back.1_0"]}
        />
        <mesh
          geometry={nodes.LIGHTS_REAR_2_CAR_lights_back1_0.geometry}
          material={materials["CAR_lights_back.1_0"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model3.glb");
