"use client";
import SideBar from "@/components/layout/SideBar";
import "./styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RecoilProvider from "@/components/RecoilProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="antialiased">
      <head />
      <body className="flex">
        <RecoilProvider>
          <main className="bg min-h-screen flex-1">{children}</main>
          <SideBar />
        </RecoilProvider>
      </body>
    </html>
  );
}
